services:
  sim:
    image: 99p_gym_sim
    container_name: 99p_gym_sim
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./src:/sim_ws/src
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    stdin_open: true
    tty: true 
  novnc:  
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=1728
      - DISPLAY_HEIGHT=972
    ports:
      - "8080:8080"
    networks:
      - x11
networks:
  x11:
