<?xml version="1.0"?>

<!-- Version 2 of Racecar - More Complicated than Simple Version -->
<robot name="racecar" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find f110_description)/urdf/macros.xacro" />

  <!-- Add chassis and it's inertia link -->

  <link name="base_link" />
  <!-- Base_Footprint Link -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  
  <link name="base_footprint" /> 
  <!-- Chassis-->
  <link name="chassis">
    <visual>
      <xacro:chassis_geometry/>
      <material name="blue" />
    </visual>
  </link>

  <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0.05" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
  </joint>

  <link name="chassis_inertia">
    <inertial>
      <xacro:chassis_inertial_params />
    </inertial>
  </link>

  <joint name="chassis_inertia_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="chassis_inertia" />
  </joint>

  <!-- Add the left rear wheel with its joints and tranmissions -->

  <link name="left_rear_wheel">
    <inertial>
      <xacro:left_wheels_inertial_params />
    </inertial>
    <visual>
      <xacro:left_rear_wheel_geometry />
      <material name="black" />
    </visual>
    <collision>robot
      <xacro:left_wheels_collision_geometry />
    </collision>
  </link>

  <joint name="left_rear_wheel_joint" type="continuous">
    <origin xyz="0 0.1 0" rpy="0 0 0" />
    <parent link="chassis" />
    <child link="left_rear_wheel" />
    <axis xyz="0 0 -1" />
    <limit effort="10" velocity="100" />
  </joint>

  <xacro:wheel_transmission name="left_rear_wheel" />

  <!-- Add the right rear wheel with its joints and tranmissions -->

  <link name="right_rear_wheel">
    <inertial>
      <xacro:right_wheels_inertial_params />
    </inertial>
    <visual>
      <xacro:right_rear_wheel_geometry />
      <material name="black" />
    </visual>
    <collision>
      <xacro:right_wheels_collision_geometry />
    </collision>
  </link>

  <joint name="right_rear_wheel_joint" type="continuous">
    <origin xyz="0 -0.1 0" rpy="1.5708 0 0" />
    <parent link="chassis" />
    <child link="right_rear_wheel" />
    <axis xyz="0 0 -1" />
    <limit effort="10" velocity="100" />
  </joint>

  <xacro:wheel_transmission name="right_rear_wheel" />

  <!-- Add the left steering hinge with its joints and tranmissions -->

  <link name="left_steering_hinge">
    <inertial>
      <xacro:steering_hinge_inertial_params />
    </inertial>
    <visual>
      <xacro:left_steering_hinge_geometry />
      <material name="grey" />
    </visual>
  </link>

  <joint name="left_steering_hinge_joint" type="revolute">
    <origin xyz="0.325 0.1 0" rpy="0 1.5708 0" />
    <parent link="chassis" />
    <child link="left_steering_hinge" />
    <axis xyz="-1 0 0" />
    <limit lower="-1.0" upper="1.0" effort="10" velocity="100" />
  </joint>

  <xacro:steering_hinge_transmission name="left_steering_hinge" />

  <!-- Add the right steering hinge with its joints and tranmissions -->

  <link name="right_steering_hinge">
    <inertial>
      <xacro:steering_hinge_inertial_params />
    </inertial>
    <visual>
      <xacro:right_steering_hinge_geometry />
      <material name="grey" />
    </visual>
  </link>

  <joint name="right_steering_hinge_joint" type="continuous">
    <origin xyz="0.325 -0.1 0" rpy="0 1.5708 0" />
    <parent link="chassis" />
    <child link="right_steering_hinge" />
    <axis xyz="-1 0 0" />
    <limit lower="-1.0" upper="1.0" effort="10" velocity="100" />
  </joint>

  <xacro:steering_hinge_transmission name="right_steering_hinge" />

  <!-- Add the left front wheel with its joints and tranmissions -->

  <link name="left_front_wheel">
    <inertial>
      <xacro:left_wheels_inertial_params />
    </inertial>
    <visual>
      <xacro:left_front_wheel_geometry />
      <material name="black" />
    </visual>
    <collision>
      <xacro:left_wheels_collision_geometry />
    </collision>
  </link>

  <joint name="left_front_wheel_joint" type="continuous">
    <origin xyz="0 0 0" rpy="1.5708 0 0" />
    <parent link="left_steering_hinge" />
    <child link="left_front_wheel" />
    <axis xyz="0 0 -1" />
    <limit effort="10" velocity="100" />
  </joint>

  <xacro:wheel_transmission name="left_front_wheel" />

  <!-- Add the left front wheel with its joints and tranmissions -->

  <link name="right_front_wheel">
    <inertial>
      <xacro:right_wheels_inertial_params />
    </inertial>
    <visual>
      <xacro:right_front_wheel_geometry />
      <material name="black" />
    </visual>
    <collision>
      <xacro:right_wheels_collision_geometry />
    </collision>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <origin xyz="0 0 0" rpy="1.5708 0 0" />
    <parent link="right_steering_hinge" />
    <child link="right_front_wheel" />
    <axis xyz="0 0 -1" />
    <limit effort="10" velocity="100"/>
  </joint>
  
  <xacro:wheel_transmission name="right_front_wheel" />

  <!-- Add Hokuyo laser scanner -->

  <link name="laser">
    <inertial>
      <xacro:hokuyo_inertial_params />
    </inertial>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://f110_description/meshes/hokuyo.dae"/>
        <material name="grey" />
      </geometry>
    </visual>
  </link>

  <joint name="hokuyo_joint" type="fixed">
    <origin xyz="0.265 0.0 0.075" rpy="0 0 0"/>
    <parent link="chassis" />
    <child link="laser" />
    <axis xyz="0 0 1" />
  </joint>


  <!-- realsense camera -->
  <xacro:include filename="$(find realsense2_description)/urdf/_d435.urdf.xacro" />
  <xacro:sensor_d435 name="camera" parent="base_link">
       <origin xyz="${wheelbase/2 + camera_length} 0 ${camera_height-ground_offset}" rpy="0 0 0"/>
  </xacro:sensor_d435>

  <!-- IMU-->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <!-- Add the remaining xacros -->

  <xacro:include filename="$(find f110_description)/urdf/racecar.gazebo" />
  <xacro:include filename="$(find f110_description)/urdf/materials.xacro" />

</robot>
